### ISSUE TITLE
Does it work by default?

### ISSUE THREAD

**Issue by pickfire** [Shougo/context_filetype.vim#20]
I found that there is nothing mentioned about the usage of context_filetype.vim. It should be mentioned in the wiki or the doc at least.

**Comment by Shougo** [comment]
No.  Because, it is used for plugins.

**Comment by pickfire** [comment]
How do you install it?

**Comment by Shougo** [comment]
Currently supported plugins: neocomplcache.vim, neocomplete.vim, neosnippet.vim, ...

**Comment by pickfire** [comment]
What does *neo* mean? And does it uses `lua` like *neovim*?

Is `lua` faster than `vim script` as ***neocomplete*** as it is slow when I use it (I mean whenever it show completion)?

**Comment by Shougo** [comment]
context_filetype.vim does not improve completion speed.
It adds extra features in the plugins.

For example, neocomplete can call python completion in ':python' line using context_filetype.vim.

**Comment by pickfire** [comment]
I mean is **neocomplete** faster if using `lua` rather than `vim script`?

Do I need to just install **context_filetype.vim** with a vim plugin manager and I can use the new features in **neocomplete**?

**Comment by Shougo** [comment]
> I mean is neocomplete faster if using lua rather than vim script?

Yes.

> Do I need to just install context_filetype.vim with a vim plugin manager and I can use the new features in neocomplete?

Yes.

**Comment by pickfire** [comment]
Thank you.
