### ISSUE TITLE
バッファローカルな filetypes 定義を追加したい。

### ISSUE THREAD

**Issue by kawaz** [Shougo/context_filetype.vim#23]
最近 dein.vim 用にtomlで hook_* 系にマッチするルールを追加してみて、これは便利だと感動しながら他にも使い所を考えてたらすぐに感じた事です。

例えばTOML一つにしても、今はまだ toml を使う機会はあまり多くありませんが、今後は色んなアプリケーションでtoml形式のファイルを扱うようになってくる予感がしています。
そうしてグローバルな `g:context_filetype#filetypes` の同じ filetype に対する設定を追加しはじめると設定の競合が起きてきそうな事と不用なパターンの検索で遅くなりそうな事を問題に感じました。

ファイル名が `dein*.toml` のときだけ toml に hook_* 系のルールを追加したいという場合は、`autocmd` で `b:context_filetype#filetypes` を定義してやることでグローバル設定と合わせてこれも使うという事が出来ると良いのかなと思います。

**Comment by Shougo** [comment]
`b:context_filetype#filetypes` `#` はバッファ変数の名前に使えません。

**Comment by Shougo** [comment]
取り敢えず追加。面倒なので形式は同じ。
