### ISSUE TITLE
not working in my case with html

### ISSUE THREAD

**Issue by wangsongiam** [Shougo/context_filetype.vim#27]
Hi there, I've tried this plugin with Deoplete and omnicomplete, and It didn't work when typing css in style tag in html. I've read the doc to try to set some values, but I found that this plugin comes with default values that should work without settings. Something wrong? more info on [this issue](https://github.com/Shougo/deoplete.nvim/issues/424)
![2017-01-30 08 14 45](https://cloud.githubusercontent.com/assets/19645990/22424722/d0c85900-e6c5-11e6-881a-0dcc4dd0140c.gif)

**Comment by Shougo** [comment]
This is deoplete issue.
