### ISSUE TITLE
HTMLファイル内のstyle属性でCSSの補完が出来ない

### ISSUE THREAD

**Issue by yoshinaga-hiroyuki** [Shougo/context_filetype.vim#37]
[neosnippet.vimのissue](https://github.com/Shougo/neosnippet.vim/issues/442)
から移ってきました
吉永です

ただ補完が出来ないと言うより、制限、仕様のような気がしていますが、念の為ご報告ということで

最後に動画を載せましたが
1. style 属性の属性値が「"」ではなく「'」で挟まれている場合は、そもそも CSS扱いにならない←これは osyo-manga/vim-precious の問題?
2. style タグ/属性どちらでも、CSS の補完が出る
3. ただし条件が有り、タグや属性名 style=と CSS のプロパティが同一行に有る場合は、補完候補が現れない

感想として
- styleタグを用いる場合は、たいてい次の行から CSS を書くので現状で何の不便もなし
- HTML の属性値内部で改行するのは、文法違反なので上の制限は少し残念

他環境は直近のissueと同じです
![context_filetype_html-css](https://user-images.githubusercontent.com/24851657/44627879-bb621a00-a970-11e8-8fb4-cea65ad4b538.gif)

**Comment by Shougo** [comment]
手元で試しましたが、該当の問題が再現しないですね。
話がややこしくなるので、 osyo-manga/vim-precious と併用しない状態でテストしてください。

**Comment by yoshinaga-hiroyuki** [comment]
>そもそも属性指定に ' は使えるのですか？
文法として不正なように見えるのですが。

勧告の原文を見ていませんが、ぐぐってみると
https://9lio.com/column/html-attribute-and-attribute-value/
等で「'」も OK と有ります
[Markup Validation Service](https://validator.w3.org/#validate_by_upload)
の文法チェックでもエラーになりません
殆どは「"」を使いますが、属性値の中身に「"」を使いたいときには「'」で挟みます
style属性でもquotesプロパティなどでは「'」を使うことが有るかと思います
ただこちらに関しては、私人も殆ど「'」は使わないので、現状の仕様でも実用上は何の問題もありません
テストしていてたまたま気が付いたので

> 話がややこしくなるので、 osyo-manga/vim-precious と併用しない状態でテストしてください。

元々無くても場所によっては CSS が働くんですね

> ちょっとこれが上の動画だと分かりにくいので、具体的なコードで教えてください。

次がサンプルの HTML です
コメントに補完候補出現の有無が記載してあります(末尾画像時に比べてコメントに若干追記しています)
```
<!DOCTYPE html>
<html lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="Content-Style-Type" content="text/css">
<title>title</title>
</head>
<style>body{co /* HTML の補完候補 commnet も CSS の補完候補 color のどちらも補完候補に出ない (オムニ補完等は出るかも知れないけど。以下も同様)*/
	ba /* CSS の補完候補が出る */
}
</style>
<body style="co"><!-- CSS の補完候補が出ない←styleの前で改行しても同様 -->
<p style="
co
"><!-- 上の行では CSS の補完候補が出る←ただし HTML の文法違反 -->
</p>
</body>
</html>
```
### お断り
明日明後日は時間が取れず、お返事を頂いてもさらなるお返事は送れます
ご容赦下さい
### 環境
#### vimrc
> $ grep -vh "^\"" ~/.vim/vimrc | sed -r -e 's/\s*".+//g' -e '/^$/d'
```
if has('vim_starting')
	if &compatible
		set nocompatible
	endif
	let s:cache_home = empty($XDG_CACHE_HOME) ? expand('~/.vim') : $XDG_CACHE_HOME
	let s:dein_dir = s:cache_home . '/bundle'
	let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
	if !isdirectory(s:dein_repo_dir)
		call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
	endif
	set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/dein.vim
	if dein#load_state(s:dein_dir)
		call dein#begin(s:dein_dir)
		let g:rc_dir = expand('~/.vim/rc')
		let s:toml = g:rc_dir . '/dein.toml'
		let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
		call dein#load_toml(s:toml, {'lazy': 0})
		call dein#load_toml(s:lazy_toml, {'lazy': 1})
		call dein#end()
		call dein#save_state()
		if dein#check_install()
			call dein#install()
		endif
	endif
endif
filetype plugin indent on
```
#### dein*.toml
> $ grep -vh "^\#" ~/.vim/rc/dein* | sed -r -e 's/^\#.+//g' -e 's/^\s*\".+//g' -e '/^$/d'
```
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'Shougo/context_filetype.vim'        # 'Shougo/neocomplete' 'Shougo/neosnippet' が依存
hook_add = '''
	if !exists('g:context_filetype#filetypes')
		let g:context_filetype#filetypes = {}
	endif
'''
[[plugins]]
repo = 'Shougo/neocomplete'                 #補完
hook_add = '''
	let g:neocomplete#enable_at_startup = 1
	let g:neocomplete#enable_ignore_case = 1
	let g:neocomplete#enable_smart_case = 1
	if !exists('g:neocomplete#keyword_patterns')
		let g:neocomplete#keyword_patterns = {}
	endif
	let g:neocomplete#keyword_patterns._ = '\h\w*' "_(アンダーバー)区切りの補完を有効化
	if !exists('g:neocomplete#force_omni_input_patterns')
		let g:neocomplete#force_omni_input_patterns = {}
	endif
	let g:neocomplete#sources#dictionary#dictionaries = { 'default' : '',}
'''
[[plugins]]
repo = 'Shougo/neosnippet'                  #補完
depends = ['context_filetype']
hook_add = '''
	imap <C-u> <Plug>(neosnippet_expand_or_jump)
	smap <C-u> <Plug>(neosnippet_expand_or_jump)
	xmap <C-u> <Plug>(neosnippet_expand_target)
	imap <C-b> <Plug>(neosnippet_expand_or_jump)
	smap <C-b> <Plug>(neosnippet_expand_or_jump)
	xmap <C-b> <Plug>(neosnippet_expand_target)
	inoremap <expr><BS> neocomplete#smart_close_popup()
	let g:neosnippet#snippets_directory = [ '~/.vim/snippet/', '~/.vim/bundle/repos/github.com/' ]
	if has('conceal')                              "補完で続けての入力を示すマーカーを入力中は非表示
		setlocal conceallevel=2 concealcursor=niv
	endif
'''
[[plugins]]
repo = 'Shougo/neosnippet-snippets'         #補完辞書
depends = ['neosnippet']
```
### それぞれの場所で補完候補で出ている時の画像
最初と3番目では、入力履歴に因る補完候補? は出ていますが、neosunippetによる補完は出ていません
![screenshot from 2018-08-26 22-57-45](https://user-images.githubusercontent.com/24851657/44629247-549c2b00-a987-11e8-90ec-9c30c840d624.png)
![screenshot from 2018-08-26 22-59-31](https://user-images.githubusercontent.com/24851657/44629248-59f97580-a987-11e8-9e33-8c881ac060d0.png)
![screenshot from 2018-08-26 22-59-47](https://user-images.githubusercontent.com/24851657/44629251-5e259300-a987-11e8-962c-f79020fe4fdf.png)
![screenshot from 2018-08-26 22-59-58](https://user-images.githubusercontent.com/24851657/44629252-6251b080-a987-11e8-9363-509f6dcafd9e.png)

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by yoshinaga-hiroyuki** [comment]
一部変わっていない変わっていない気がしますので、ちょっと確認させて下さい
### context_filetype のアップデート結果
>From https://github.com/Shougo/context_filetype.vim
   ec1bb48..71e19b3  master     -> origin/master
remote: Counting objects: 8, done.

### サンプル HTML (変化なし)
```
<!DOCTYPE html>
<html lang="ja">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta name="Content-Style-Type" content="text/css">
<title>title</title>
</head>
<style>body{co /* HTML の補完候補 commnet も CSS の補完候補 color のどちらも補完候補に出ない (オムニ補完等は出るかも知れないけど。以下も同様)*/
	ba /* CSS の補完候補が出る */
}
</style>
<body style="co"><!-- CSS の補完候補が出ない←styleの前で改行しても同様 -->
<p style="
co
"><!-- 上の行では CSS の補完候補が出る←ただし HTML の文法違反 -->
</p>
</body>
</html>
```
### 変わった点
```
<p style="
co
"><!-- 上の行では CSS の補完候補が出る←ただし HTML の文法違反 -->
```
で「"」を「'」に変更しても、CSSの候補が出るようになりました
ありがとうございます
### やはり CSS の候補が出て来ませんが、これは仕様でしょうか?
上記のようなCSSの書き始めがタグ/属性それぞれで別行に有るケースでは、以前通り変換候補が出ます
出ないのは次のstyleタグ/属性が同一行に有るケースです
#### styleタグのとき
![style-tag_no-snipeet](https://user-images.githubusercontent.com/24851657/44717420-e75bd780-aaf7-11e8-8afc-df6482d16e88.png)
#### style属性の時
![style_no-snipeet](https://user-images.githubusercontent.com/24851657/44718219-5e926b00-aafa-11e8-9378-5fe06ade6332.png)

**Comment by Shougo** [comment]
もうしわけありませんが、上記を再現するために具体的に実行したキーマップを教えてください。
具体的にどの行のどのカラムから 'i' や 'a' を実行して挿入モードに入り、補完を実行したのか。
これが非常に重要なのです。

これが教えてもらえない場合は修正不能なのです。
こちらで再現しない問題は close されたままとさせてもらいます。

**Comment by yoshinaga-hiroyuki** [comment]
### 回答に対する返信概要
> もうしわけありませんが、上記を再現するために具体的に実行したキーマップを教えてください。

提示した例は補完を開始する何か特別なキーマップは実行していないです
> 具体的にどの行のどのカラムから 'i' や 'a' を実行して挿入モードに入り、補完を実行したのか。
これが非常に重要なのです。

どちらの画像も補完をするためにキーマップを実行したわけでなく、2文字以上入力し、自動で補完候補が出たタイミングの画像です
前者は'col'と3文字入力した時になっていましたm(\_|\_)m
### サンプルHTML 8行目を用いた具体例
#### CSSが途中まで入力されている時
```
<style>body{co /* HTML の補完候補 commnet も CSS の補完候補 color のどちらも補完候補に出ない (オムニ補完等は出るかも知れないけど。以下も同様)*/
```
で'co'の'o'の位置 (14桁目) にあるノーマルモードからなら
clo
やそのまま続きを入力するために
al
挿入モードからなら
&lt;C-h&gt;o
やこちらもそのまま続き
l
を入力している等の挿入モードで2文字以上入力した時の例の画像になります
#### CSSが未入力の時
```
<style>body{ /* HTML の補完候補 commnet も CSS の補完候補 color のどちらも補完候補に出ない (オムニ補完等は出るかも知れないけど。以下も同様)*/
```
の状態からだと、'{'の位置なら
aco
もしくはその次に空白位置なら
ico
とタイプした時、こちらもとにかく2文字以上入力された時の挿入モードになります

**Comment by Shougo** [comment]
Fixed.

**Comment by yoshinaga-hiroyuki** [comment]
一応ご報告として
> From https://github.com/Shougo/context_filetype.vim
   71e19b3..5392e3f  master     -> origin/master
Unpacking objects: 100% (10/10), done.
From https://github.com/Shougo/neosnippet-snippets
   611b0fc..a2e90c4  master     -> origin/master
Updating 71e19b3..5392e3f
Fast-forward
Updating 611b0fc..a2e90c4
 autoload/context_filetype.vim | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Fast-forward
 neosnippets/c.snip    | 16 ++++++++++++----
 neosnippets/java.snip | 16 ++++++++++++++--
 2 files changed, 26 insertions(+), 6 deletions(-)

とアップデート後、
```
call dein#recache_runtimepath()
```
を念の為実行しましたが、style属性/タグとCSSが同一行にあるような
```
<style>body{
```
に続けて挿入モードで'co'を入力したり、
```
<body style="">
```
で「"」に挟まれている間で、挿入モードで'co'を入力しても、neosnippetによる補完候補は出ないままです
- 既にcontext_filetypeではなく、neosnippetの問題の気がする
- 当初のHTML内のstyle属性/タグ以外の場所でCSSが補完候補として出てきてしまう問題(ol→outlineとなる)は解決済み
- Shogoさんにこちらの意図が伝わっていない、もしくはそちらの環境で再現していないという事のような気がしている

ということで、このままクローズして頂いても構いません

neosnippetを使って補完をしたい時は、一旦改行して後から行連結すれば、済む問題でも有るので
