### ISSUE TITLE
VueJS custom block

### ISSUE THREAD

**Issue by RageYL** [Shougo/context_filetype.vim#38]
Hi,

Would it be possible to add support for VueJS custom blocks ? The custom blocks can have any name:

```
<someName>
</someName>
```

Here, get_filetype() could return someName or vue-someName. This would be useful for toggling comments inside those blocks. (currently i'm copying the default configuration for vue and adding each custom block manually)

Thanks.

**Comment by Shougo** [comment]
Unfortunately, it cannot be supported.

> The custom blocks can have any name:

This is impossible reason.
It has any names and any filetypes.

**Comment by Shougo** [comment]
If it is fixed pattern and filetypes, it can be supported.

**Comment by RageYL** [comment]
Actually I asked this question because I'm not familiar at all with vimscript regex and wasn't sure it was feasible. Here is something close to what it should do (```<lang="lol">``` should be ```<lol>```)

```
\   {
\    'start':
\     '<\%(lang="\%(\(\h\w*\)\)"\)\%( [^>]*\)\?>',
\    'end': '</\1>', 'filetype': '\1',
\   },
```

Do you think it is still impossible ?

**Comment by Shougo** [comment]
It is possible, but it is not matched to Vue.js custom blocks.
Because the filetype is not equal to block name.
It can be any filetypes.

**Comment by RageYL** [comment]
I'm not sure i'm understanding what you mean. 

But adding 2 rules, one that set the filetype to the block name if no lang attribute is present and a second one that set the filetype to the value of the lang attribute would imo be a good solution.

**Comment by Shougo** [comment]
I don't understand why you don't understand.
You should read Vue.js custom blocks specification.
It cannot be ruled.

**Comment by Shougo** [comment]
https://vue-loader.vuejs.org/guide/custom-blocks.html#example

If blocks doesn't have lang, it can be block name?
It is still useful?

**Comment by RageYL** [comment]
Yes it is ! =)

I can specify in advance the commentstring for filetype "foo", and inside a block ```<foo>some text</foo>```. I would be able to toggle comment using the proper commentstring and not the default html string. (because context_filetype would return "foo" and not "vue")

**Comment by Shougo** [comment]
OK.  I understand.
