### ISSUE TITLE
Problem with svelte and deoplete

### ISSUE THREAD

**Issue by daliusd** [Shougo/context_filetype.vim#39]
I have added following lines to my .vimrc:

```
if !exists('g:context_filetype#same_filetypes')
    let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.svelte =
            \ [
            \    {'filetype' : 'javascript', 'start' : '<script>', 'end' : '</script>'},
            \    {'filetype' : 'css', 'start' : '<style>', 'end' : '</style>'},
            \ ]
```

This helps with javascript autocompletion but css autocompletion does not work.

Adding this helps with css autocomplete but I think this shouldn't be necessary:
```
autocmd FileType svelte setlocal omnifunc=csscomplete#CompleteCSS
```

Any ideas what's wrong?

My .vimrc can be found here https://github.com/daliusd/cfg/blob/master/.vimrc if it is necessary.

**Comment by Shougo** [comment]
You should read deoplete documentation and understand features.

```vim
call deoplete#custom#source('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS']
\})
```

deoplete is very smart if you know the features.

**Comment by daliusd** [comment]
Shougo, I'm happy that there are two ways how to say to deoplete where to look for css omnifunc but my concern is different. The problem is that when I open css file I get omnifunc=csscomplete#CompleteCSS automatically and deoplete uses that. That's awesome. Now when I use context_filtype.vim for file that has JS, CSS and HTML/Svelte in one file then CSS autocompletion is not working out-of-the box and I need to do something about that (mine or your solution). I'm pretty sure that .vue files have the same problem.

I can live with current workarounds but IMHO that shouldn't be requirement for CSS.

I think this is the same problem as here with CSS: https://github.com/Shougo/deoplete.nvim/issues/424

**Comment by daliusd** [comment]
BTW, your proposal does not seem to be necessary or does not seem to change anything. I must note that autocomplete actually works but only partially and omni completions are not working. Here is how autocomplete looks like with my workaround:

![1](https://user-images.githubusercontent.com/1944737/62192372-2fc1ec00-b37e-11e9-94fe-eef8ef5b69a4.png)

Omni completions are shown with [O] and there are other autocompletions. With my workaround I can even get potential values:

![2](https://user-images.githubusercontent.com/1944737/62192373-2fc1ec00-b37e-11e9-9319-304a6d233e69.png)

Your proposal does not enable omnifunc ([O]) autocompletions.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS']
\})
```

This is the correct.

**Comment by Shougo** [comment]
And please use the latest version of deoplete.

**Comment by daliusd** [comment]
Thanks for fixing this. You are awesome!!!
