### ISSUE TITLE
javascript in html can't work

### ISSUE THREAD

**Issue by yangxyo** [Shougo/context_filetype.vim#41]
```
if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.svelte = [
\ {'filetype' :'javascript', 'start': '<script>', 'end': '</script>'},
\ {'filetype' :'css', 'start': '<style>', 'end': '</style>'},
\ ]
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS'],
\})
```

It let css-completion work,
but javascript doesn't work with YCM, inside HTML.

Even with deoplete, comment out the YCM.
```
call deoplete#custom#option('omni_patterns', { 
\ 'javascript': '[^. *\t]\.\w*',
\ 'go': '[^. *\t]\.\w*',
\})
```
In .js it work.
But in html it doesn't work too.

**Comment by Shougo** [comment]
You have not uploaded reproduce step.
I will close it later.

**Comment by Shougo** [comment]
You should read other issues.
https://github.com/Shougo/context_filetype.vim/issues/39#issuecomment-516734193
https://github.com/Shougo/context_filetype.vim/issues/38#issuecomment-466834409

Other people reports are better than yours.

**Comment by Shougo** [comment]
If you upload reproduce steps, I will reopen it.

**Comment by yangxyo** [comment]
Sorry, what is reproduce step.

**Comment by yangxyo** [comment]
work
![image](https://user-images.githubusercontent.com/32320149/75984513-85b6cd80-5f25-11ea-9bb6-d16264ac1be3.png)
work
![image](https://user-images.githubusercontent.com/32320149/75984554-9f581500-5f25-11ea-8ce8-1067cecfd0a1.png)
nothing
![image](https://user-images.githubusercontent.com/32320149/75984592-b0a12180-5f25-11ea-8152-40e7cf0f6680.png)

**Comment by yangxyo** [comment]
I may know the 'reproduce steps'.
I have added following lines to my .vimrc:
```
if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.svelte = [
\ {'filetype' :'javascript', 'start': '<script>', 'end': '</script>'},
\ {'filetype' :'css', 'start': '<style>', 'end': '</style>'},
\ ]
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS'],
\})
```
It lets css-completion work, but javascript doesn't work with YCM, inside HTML.

then to add following lines to my .vimrc:
```
call deoplete#custom#option('omni_patterns', { 
\ 'javascript': '[^. *\t]\.\w*',
\ 'go': '[^. *\t]\.\w*',
\})
```
In .js it work.
But in html it doesn't work too.

**Comment by Shougo** [comment]
OK.  I will check the issue.

**Comment by yangxyo** [comment]
Thanks。
