### ISSUE TITLE
javascript inside HTML error

### ISSUE THREAD

**Issue by yangxyo** [Shougo/context_filetype.vim#42]
I have added following lines to my .vimrc:
```
if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.svelte = [
\ {'filetype' :'javascript', 'start': '<script>', 'end': '</script>'},
\ {'filetype' :'css', 'start': '<style>', 'end': '</style>'},
\ ]
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS'],
\})
```
It lets css-completion work, but javascript doesn't work with YCM, inside HTML.

then to add following lines to my .vimrc:
```
call deoplete#custom#option('omni_patterns', { 
\ 'javascript': '[^. *\t]\.\w*',
\ 'go': '[^. *\t]\.\w*',
\})
```
In .js it work.
But in html it doesn't work too.

_Originally posted by @yangxyo in https://github.com/Shougo/context_filetype.vim/issues/41#issuecomment-595223533_

**Comment by yangxyo** [comment]
<c-x> <c-o> work in .js .
![image](https://user-images.githubusercontent.com/32320149/75989725-bb13e900-5f2e-11ea-8761-0f019509f720.png)

<c-x><c-o> doesn't work in .html
![image](https://user-images.githubusercontent.com/32320149/75989812-e565a680-5f2e-11ea-9ec7-3d002f45b16f.png)

**Comment by yangxyo** [comment]
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)

**Comment by yangxyo** [comment]
```
Plug 'Shougo/deoplete.nvim' | Plug 'roxma/nvim-yarp' | Plug 'roxma/vim-hug-neovim-rpc
Plug 'Shougo/context_filetype.vim'
```

```
" => deoplete ---------------------------------
let g:deoplete#enable_at_startup = 1
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

if !exists('g:context_filetype#same_filetypes')
  let g:context_filetype#filetypes = {}
endif
let g:context_filetype#filetypes.svelte = [
\ {'filetype' :'javascript', 'start': '<script>', 'end': '</script>'},
\ {'filetype' :'css', 'start': '<style>', 'end': '</style>'},
\ ]
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS'],
\})
call deoplete#custom#option('omni_patterns', { 
\ 'go': '[^. *\t]\.\w*',
\ 'javascript': '[^. *\t]\.\w*',
\})
inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#mappings#manual_complete()
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

```

**Comment by yangxyo** [comment]
I researched this all day. 😭 ... Thanks.

**Comment by Shougo** [comment]
It just your configuration problem.
Please wait...

**Comment by yangxyo** [comment]
Hey, darling.

**Comment by yangxyo** [comment]
I've see all the doc of `context_filetype`, and still can't solve it.

**Comment by Shougo** [comment]
I will update deoplete documentation

**Comment by yangxyo** [comment]
Then, what happen to me, can you tell me.

**Comment by yangxyo** [comment]
I really don't want to use the  completion sources for javascript, they need too many steps to install them, and require so many dependencies. unlike YCM just do `Plug 'ycm-core/YouCompleteMe', { 'do': function('BuildYCM')} `
This `context_filetype` can support to YCM?
![image](https://user-images.githubusercontent.com/32320149/76057971-07563c00-5fb6-11ea-9aea-d1524949b794.png)

**Comment by yangxyo** [comment]
If use the `autozimu/LanguageClient-neovim`, I really don't like that another server run behind my computer.

**Comment by Shougo** [comment]
YCM doesn't support context_filetype.

**Comment by yangxyo** [comment]
```
call deoplete#custom#option('omni_patterns', { 
\ 'go': '[^. *\t]\.\w*',
\ 'javascript': '[^. *\t]\.\w*',
\})
```
But it also don't work for me😭.

**Comment by Shougo** [comment]
I am at work.  I cannot update the documentation now.
Please wait.

**Comment by yangxyo** [comment]
hey,  brother, don't forget it.

**Comment by Shougo** [comment]
```
       call deoplete#custom#var('omni', 'input_patterns', {
       \ 'javascript': '[^. *\t]\.\w*',
       \ })
	call deoplete#custom#var('omni', 'functions', {
	\ 'javascript': ['javascriptcomplete#CompleteJS']
	\})
```

**Comment by yangxyo** [comment]
```
let g:context_filetype#filetypes.svelte = [
\ {'filetype' :'javascript', 'start': '<script>', 'end': '</script>'},
\ {'filetype' :'css', 'start': '<style>', 'end': '</style>'},
\ ]
call deoplete#custom#var('omni', 'functions', {
\ 'css': ['csscomplete#CompleteCSS'],
\ 'javascript': ['javascriptcomplete#CompleteJS'],
\})
call deoplete#custom#option('omni_patterns', { 
\ 'go': '[^. *\t]\.\w*',
\ 'javascript': '[^. *\t]\.\w*',
\})
```
It doesn't work 😅.

**Comment by yangxyo** [comment]
Ok, thanks, awesome man.

**Comment by yangxyo** [comment]
![image](https://user-images.githubusercontent.com/32320149/76083987-d7c12700-5fe9-11ea-8c12-524545ed80e6.png)

**Comment by Shougo** [comment]
Yes.  deoplete and context_filetype are real power.
