### ISSUE TITLE
filetypedetection is a little weird with comments

### ISSUE THREAD

**Issue by aMOPel** [Shougo/context_filetype.vim#49]
Hi there, love your work, 
am using dein with toml configuration and im using [caw](https://github.com/tyru/caw.vim) for commenting which uses context_filetype.

in the gif im trying to show that the context_filetype is behaving a little weird with comments.
normally when at the end of a multiline comment in toml (''') the detected filetype is toml, but when i comment the line out it becomes vim.
i try to show this by moving around and echoing g:context_filetype#get_filetype() in diffrent places, commented and not.

in the end you can see when i try to toggle the comments for block and my cursor ends up at the bottom, it detects vim filetype and creates new vim comments instead of removing the toml comments.
but if i end up at the top where it detects toml it uncomments.

![context_filetype_comment](https://user-images.githubusercontent.com/36712072/117699921-acc1fc80-b1c5-11eb-9091-5b11d31b08ad.gif)

**Comment by Shougo** [comment]
Sorry.  context_filetype plugin is not magic.
The comment out is not detected easily.
And I don't think it is issue.

**Comment by aMOPel** [comment]
@Shougo I understand that this is not easy. I don't think you should implement magic here. 
I don't understand why you detect a contexted filetype in a commented line in the first place, since everything in a comment from the main filetype is just text. 

Are there really any use cases for detecting the context filetype in a comment?

Maybe an option to turn this off would be nice, since I think all commenter plugins which use context filetype could suffer from similar issues.

**Comment by Shougo** [comment]
> I don't understand why you detect a contexted filetype in a commented line in the first place, since everything in a comment from the main filetype is just text.

If you can, please send the PR!  It is open source.  No magic.

**Comment by aMOPel** [comment]
thanks very much. ive tried it but it doesn't seem to be working for me. But maybe ive misunderstood smth.

![context_filetype_ignore_pattern](https://user-images.githubusercontent.com/36712072/117824108-7a200e80-b26e-11eb-92eb-83cbb2e7e9f9.gif)

**Comment by aMOPel** [comment]
> Please use the config instead.
> 
> ```viml
> let g:context_filetype#ignore_patterns = {
>     \ 'toml': ['^\s*#\s*'],
>     \ }
> ```
> 
> NO magic.

works indeed, thank you very much for helping me. Maybe you want to update the helpfile if you didnt already, adding the additional '\s*'
