### ISSUE TITLE
Neovim could be blocked for more than a second somtimes.

### ISSUE THREAD

**Issue by chemzqm** [Shougo/context_filetype.vim#54]
When this plugin enabled and using nvim >= 0.6.0 with iTerm2 on Mac, nvim could be blocked for more than a second sometimes.

To reproduce, type command `:h a` and `:h b` many times.

My computer:

```
MacOS 12.1
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB 2667 MHz DDR4
```

No happens on vim8 or other terminal.

**Comment by Shougo** [comment]
Please upload the minimal configuration.
I will test it.

**Comment by chemzqm** [comment]
Can't reproduce any more...
