### ISSUE TITLE
Vim help support filetype specification

### ISSUE THREAD

**Issue by tsuyoshicho** [Shougo/context_filetype.vim#57]
https://github.com/Shougo/context_filetype.vim/blob/7ff5b43fc8d5b274aa19ade5af11e9fa57577ed6/autoload/context_filetype/defaults.vim#L97-L103

https://github.com/vim/vim/pull/16215
にて Neovim からのインポートで Vim の help のコードブロックについてファイルタイプアノテーションがサポートされました。

どこかで対応を入れないとですね

**Comment by tsuyoshicho** [comment]
あと、このendはちょっと間違ってる気がしますね
空行で終了しちゃうと、(たしかに誤記かもしれませんが)途中でファイルタイプのブロック判定が終了しちゃう気がします。

* 次の行(先頭が通常文字)
* `<` で終了する

の2種かと思います。

```
end: '^<\|^\S', 
```

ですかね?

**Comment by Shougo** [comment]
Implemented.
